//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace warehouse.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int PriceId { get; set; }
        public Nullable<int> GoodsId { get; set; }
        public Nullable<decimal> PriceAmount { get; set; }
    
        public virtual Goods Goods { get; set; }
    }
}
