//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace warehouse.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerBooking
    {
        public int WorkerBookingId { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public Nullable<int> BookingId { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
